### ISSUE TITLE
Functionality Enhancement 1: Themes

### ISSUE THREAD

**Issue by Jessica-Henry** [HoltHunter/Group-12#60]
This is an issue to track the development of a new functionality for the 2nd release.

**Comment by hellojoelhuber** [comment]
* Add db field: user.theme
* Add endpoints to set, retrieve theme (retrieve probably only needs to be included in the Login response)
* Add state property in App: theme, with classic theme default
* Set theme state on login based on returned value
* User settings screen to change theme

**Comment by hellojoelhuber** [comment]
Note: when setting a new theme, we need to send it to the server AND update the App state property.
