### ISSUE TITLE
Functionality Enhancement 2: Profile Icons

### ISSUE THREAD

**Issue by Jessica-Henry** [HoltHunter/Group-12#61]
This is an issue to track the development of a new functionality for the 2nd release.

**Comment by hellojoelhuber** [comment]
* Add db value: users.profile_icon
* New page to set the user profile icon (can be same settings page as theme)
* Posts/ Comments/ Profile should display selected profile_icon
* Profile icons are the 6 options Jessica drew for us

**Comment by hellojoelhuber** [comment]
Note: when setting a new icon, we need to send it to the server AND update the App state property.
